### ISSUE TITLE
Feature: subscribing other filter rules

### ISSUE THREAD

**Issue by alexanderadam** [iamadamdev/bypass-paywalls-chrome#1140]
So, it is impossible to bypass every possible domain, which is why you applied some [rules for new site requests](https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests) and of course your time is limited too. It would be impossible keeping everything up to date.

Thus I thought that it might be useful to add a general configuration, DSL or ruleset that could be recycled.

I agree that this is probably not trivial but _if_ it can be done, all these rules could be easily reused and this would enable subscribing 'regional' bypass lists (similar to adblock lists).

For instance:
```yaml
on_urls: ['telegraaf.nl']
variable_map:
  articleWrapper: '.ArticlePageWrapper__uid'
  spotXBanner: '.ArticleBodyBlocks__inlineArticleSpotXBanner'
  paywall: '.PopupBackdrop__block'
  premium: '.PremiumLabelWithLine__body'
  articleId: articleWrapper.innerText : '123
  articleBodyDone: '#articleBody' + articleId
  articleBodyOld: '[id^=articleBody]'
  json: 'script[type="application/ld+json"][data-react-helmet="true"]'
block_elements:
  - ['spotXBanner', 'paywall']
  - ['articleBodyOld']
 maybe_some_emergency_eval: >
  foo();
  bar(baz);

```

**PS:** Thank you so much for your work! :pray:
